runtime: go
api_version: go1

env_variables:
  GCLOUD_PROJECT: particle-volt
  PUBSUB_TOPIC: CAR

handlers:
- url: /.*
  script: _go_app

- url: /ui/
  static_dir: public/ui/

builtins:
- remote_api: on

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^.*node_modules(/.*)?
