runtime: go
api_version: go1

env_variables:
  GCLOUD_PROJECT: particle-volt
  PUBSUB_TOPIC: CAR

handlers:
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.js$
- ^(.*/)?.*src\/golang(.*/)?.*$
- ^(.*/)?.*src\/orahub(.*/)?.*$
- ^(.*/)?.*src\/github(.*/)?.*$
- ^(.*/)?.*node_modules(.*/)?.*$
- ^(.*/)?.*camlistore(.*/)?.*$
- ^(.*/)?.*fitkiq(.*/)?.*$
- ^(.*/)?.*src\/code\.google(.*/)?.*$
- ^(.*/)?.*src\/rmn(.*/)?.*$
- ^(.*/)?.*rsc\.io(.*/)?.*$
- ^(.*/)?.*build(.*/)?.*$
- ^(.*/)?\.js$
- ^(.*/)?\.md$
- ^(.*/)?\.yaml$
- ^(.*/)?.*public(.*/)?.*$
