runtime: go
api_version: go1

env_variables:
  GCLOUD_PROJECT: particle-volt
  PUBSUB_TOPIC: CAR

handlers:
- url: /static
  static_dir: build/static

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /.*
  script: _go_app

builtins:
- remote_api: on

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^.*node_modules(/.*)?
