runtime: go
api_version: go1

env_variables:
  GCLOUD_PROJECT: particle-volt
  PUBSUB_TOPIC: CAR

handlers:
- url: /public
  static_dir: public

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /bundle.js
  static_files: public/bundle.js
  upload: public/bundle.js

- url: /.*
  script: _go_app

builtins:
- remote_api: on

skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^.*node_modules(/.*)?
